# Generated by Django 3.2.9 on 2022-01-10 08:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_token_token_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='expires_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='token',
            name='token_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
