# Generated by Django 3.2.9 on 2022-05-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ariza_e'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ariza_e',
            name='place',
        ),
    ]
