# Generated by Django 3.2.9 on 2022-05-18 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220518_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ariza_e',
            name='ariza_pdf',
        ),
        migrations.RemoveField(
            model_name='ariza_e',
            name='bank_cardnumber',
        ),
        migrations.RemoveField(
            model_name='ariza_e',
            name='bank_inn',
        ),
        migrations.RemoveField(
            model_name='ariza_e',
            name='bank_mfo',
        ),
        migrations.RemoveField(
            model_name='ariza_e',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='ariza_e',
            name='bank_tr',
        ),
        migrations.RemoveField(
            model_name='ariza_e',
            name='checking',
        ),
        migrations.RemoveField(
            model_name='ariza_e',
            name='exampaper_pdf',
        ),
        migrations.RemoveField(
            model_name='ariza_e',
            name='fathersname',
        ),
        migrations.RemoveField(
            model_name='ariza_e',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='ariza_e',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='ariza_e',
            name='passport_pdf',
        ),
        migrations.RemoveField(
            model_name='ariza_e',
            name='pinfl',
        ),
        migrations.RemoveField(
            model_name='ariza_e',
            name='placeofwork_pdf',
        ),
    ]
