# Generated by Django 3.2.9 on 2022-05-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220518_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariza_e',
            name='ariza_pdf',
            field=models.FileField(default=None, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='ariza_e',
            name='bank_cardnumber',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='ariza_e',
            name='bank_inn',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='ariza_e',
            name='bank_mfo',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='ariza_e',
            name='bank_name',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='ariza_e',
            name='bank_tr',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='ariza_e',
            name='checking',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ariza_e',
            name='exampaper_pdf',
            field=models.FileField(default=None, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='ariza_e',
            name='fathersname',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='ariza_e',
            name='firstname',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='ariza_e',
            name='lastname',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='ariza_e',
            name='passport_pdf',
            field=models.FileField(default=None, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='ariza_e',
            name='pinfl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ariza_e',
            name='placeofwork_pdf',
            field=models.FileField(default=None, upload_to='pdfs/'),
        ),
    ]
