# Generated by Django 3.2.9 on 2022-05-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220518_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='example_pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_pdf', models.FileField(default=None, upload_to='pdfs/')),
            ],
        ),
    ]
