# Generated by Django 3.2.9 on 2022-05-19 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_example_pdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='example_pdf',
        ),
    ]
